name: Python CI
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [ released ]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

  docker-deploy:
    runs-on: ubuntu-latest
    needs:
      - linting
    if: github.ref == 'refs/heads/master' || (github.event_name == 'release' && github.event.action == 'released')
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - uses: docker/setup-buildx-action@v2
    - name: Dockerhub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Deploy Master
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/web/Dockerfile
        push: true
        tags: kuzirashi/safe-transaction-service:staging
        platforms: |
          linux/amd64
          linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max